#!/bin/bash
exec >hwlatdetect-client-stderrout.txt
exec 2>&1

. /usr/bin/hwlatdetect-base || (echo "/usr/bin/hwlatdetect-base not found"; exit 1)

dump_runtime
validate_label
validate_sw_prereqs

# defaults
duration=60
threshold=1us

longopts="duration:,threshold:,width:,cpumask:,utility:"
opts=$(getopt -q -o "c:d:t:w:u:" --longoptions "$longopts" -n "getopt.sh" -- "$@");
eval set -- "$opts";
while true; do
    case "$1" in
        -c|--cpumask)
            shift
            cpumask=$1
            shift
            ;;
        -d|--duration)
            shift
            duration=$1
            shift
            ;;
        -t|--threshold)
            shift
            threshold=$1
            shift
            ;;
        -c|--width)
            shift
            width=$1
            shift
            ;;
        -u|--utility)
            shift
            utility=$1
            shift
            ;;
        --)
            shift;
            break
            ;;
        *)
            shift
            ;;
    esac
done

cmd="hwlatdetect --duration=${duration} --threshold=${threshold}"

if [ -n ${utility} ]; then
    echo "utility: $utility"
    if [ "${utility}" = "no" ]; then
         echo "Manual tracer mode on: The utility will NOT be used."
         cpumask_arg=""
         if [ -n ${cpumask} ]; then
              cpumask_arg="--cpumask=${cpumask}"
         fi
         width_arg=""
         if [ -n ${width} ]; then
              width_arg="--cpumask=${width}"
         fi
         cmd="manual-hwlatdetect --duration=${duration} --threshold=${threshold} ${cpumask_arg} ${width_arg}"
    fi
else
    utility="yes"
fi

if [ "${utility}" != "no" ]; then
     if [ -n ${cpumask} ]; then
           echo "Error: cpumask is not supported by the utility, set utility=no to run on manual mode."
           exit 1
     fi
     if [ -n ${width} ]; then
           echo "Error: width is not supported by the utility, set utility=no to run on manual mode."
           exit 1
     fi
fi

echo "About to run: $cmd"
date +%s.%N >begin.txt
$cmd >hwlatdetect-bin-stderrout.txt 2>&1
date +%s.%N >end.txt

if grep -q "test finished" hwlatdetect-bin-stderrout.txt; then
    rc=0
else
    rc=1
fi

if [ $rc -gt 0 ]; then
    exit_error "`cat hwlatdetect-bin-stderrout.txt`"
fi
